name: 'ci'
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: npm install

      - run: npm run build:docs

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/docs

      - run: npm test -- --url ${{ github.event.deployment_status.target_url }}

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
